### ISSUE TITLE
SyncLoginPassword preference does not work (in El Cap?)

### ISSUE THREAD

**Issue by sheagcraig** [macmule/ADPassMon#55]
In testing, I cannot for the life of me get the
`defaults write com.apple.keychainaccess SyncLoginPassword -bool false` to prevent the keychain sync dialog from appearing at the loginwindow.

I've tried manually running (ensuring that the preference is correctly set in my user's preferences) as well as automated it with an outset login-once script performing the defaults write.

I'm running 10.11.3 on my machine. To be fair, I haven't tested it on any others.

Also, I realize that if this doesn't work, it's not _your_ fault! I'm just wondering if either something has changed and the wiki documentation just needs to be updated, or a caveat needs to be added mentioning under what versions this actually works.

Thanks!

**Comment by croaker-1** [comment]
Coincidentally, I have spent the last 2 days struggling with the same issue. I ended up writing a Launch Agent that would reliable set that preference to `true` (even after it is changed to `false` by Keychain Access while manually changing the keychain password) only to discover that it didn't matter...the dialog pops up every time.

After some research, my suspicion is this behavior was changed by 10.11.2 and, possibly, 10.11.1 which are detailed below.

**OS X El Capitan 10.11.2**
**• Keychain Access**
Available for: OS X El Capitan v10.11 and v10.11.1
Impact: A malicious application may be able to masquerade as the Keychain Server.
Description: An issue existed in how Keychain Access interacted with Keychain Agent. This issue was resolved by _removing legacy functionality.*_

**OS X El Capitan 10.11.1**
**• SecurityAgent**
Available for: OS X El Capitan 10.11
Impact: A malicious application can programmatically control keychain access prompts
Description: A method existed for applications to create synthetic clicks on keychain prompts. This was addressed by disabling synthetic clicks for keychain access windows.

I'm also on 10.11.3. I'm not sure it ever worked in 10.11 but I may do some testing. The machine I'm writing this on is running 10.11.1 so I may test out part of my theory now.

I'm glad I'm not alone! I've been searching everywhere and this is the first mention of this problem I've seen.

Update: This issue seems to exist in 10.11.1 as well.

**Comment by sheagcraig** [comment]
Hmmm. Yeah, I was aware of the "synthetic keychain clicks" issue, but it didn't occur to me that it would also apply to the loginwindow keychain sync dialog. That would be a bummer if (which they almost certainly did) remove that preference. They could have at least taken the opportunity to improve the wording on it!

**Comment by macmule** [comment]
Bugger. 

I added that to the wiki as have been using it for years. 

Sadly not deploying 10.11 yet. :(

Hmm.

**Comment by macmule** [comment]
@sheagcraig & @croaker-1, did either of you try & set the key via a profile?

**Comment by sheagcraig** [comment]
I'm set on this one. I had machines with the profile and standard settings
conflicting that were causing the issue for me.

**Comment by apizz** [comment]
I was having issues getting this to work with the user preference.  Switched to profile (comp level) and still no luck getting the keychain prompt to trigger at login.  The OSX keychain sync has been disabled.  The only way I've successfully gotten the ADPM keychain sync prompt to appear is by manually refreshing the kerberos ticket from the menubar

**Comment by macmule** [comment]
Hi folks,

ADPassmon is no longer maintained, please use [NoMAD](https://www.nomad.menu).

As such, i'm closing this off.
